language: python

python:
- '3.6'

before_install:
- sudo apt-get update -qq
- sudo apt-get install default-jdk
- sudo wget https://github.com/TheThirdOne/rars/releases/download/v1.3.1/rars1_3_1.jar
- sudo mkdir /sml
- export SMLROOT=/sml
- echo $SMLROOT
- sudo wget http://smlnj.org/dist/working/110.78/config.tgz
- sudo tar -C /sml -xzvf config.tgz
- cd /sml
- sudo config/install.sh
- sudo apt-get install gcc-multilib ia32-libs
# - sudo apt-get install smlnj
# - sudo apt-get install ml-yacc
# - sudo apt-get install ml-lex
# - sudo apt-get install -y texlive-full
# - sudo apt-get install -y texlive-xetex
# - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
# - sudo dpkg -i pandoc-2.7.3-1-amd64.deb

install:
  - pip install -r requirements.txt
  
script: "python3 ./travis/build.py"

env:
  global:
  - secure: AlBOGiHnkOAzTXYDkUOjKm6zYsms5qSDQ+UBB2pYE+d0rOXdnkBU0PwU/tEKys8wcpyTr5QNWruR8pu612pwyMSWWX63YpTSultZ7NboEzhpWLLVbmYIqozLbw/0t1oMwn48gO0AHuP+V2hWRVM9RPQW0uyH6j0lF5PPdDjybUtypbuJHIo9fjGUCuH5Ke3rcO9esXBq/q9D5/jCSN5Jm8blsdRVQhKLnCxfxAnXFp4lV7v3L/TKUe1MG7vHSrUjIShAzc0kkY3NV/NlKSX4W9Vah0FXfTj5vVQ70CmhW8hfX8tGPB40IQyuz3aPy5BjxzI+ZovPo26g9nlmZO8/eK6SM5MO5Fn/eDCG6d2+GQOAUhj1I39pBsdCjLTl6QGFyQDrW19DUWVzHx2NTXJj4cHP5t1ahme2HaIHaBylTnq6FotI+JqiIoQEbQJpKwNiBxxQYiXkFYfCOMCKgwx7bmhMeY/H1eAgkH5srX+5Ry+lmyKqfmUsTlyvgNTttsmwzBu3Qg5d6DZjXy7J8lgcaCwF8IPXjVCzQQtJNsZIxUvxLmY/VFqBbZI+HK8ojQ1cwmo2xPw41ae/AZ85bRAdtfVCZpPlQsnSzzd4/UHYyV4TVm7MS0YSt/SIETmACiycp35ao8q8BcUzw+Vubpl/GfHGP7Fwxq+ufumgzAdDoVo=
  - GH_USER_NAME: sourabh2311
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
